version: '3.11.3'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      interval: 5s
      retries: 10
  redis:
    image: redis
    ports:
      - 6379:6379
